### ISSUE TITLE
[Bug] resize for flex container is not working

### ISSUE THREAD

**Issue by purpose233** [VisActor/VChart#3910]
### Version

1.13.7

### Link to Minimal Reproduction

null

### Steps to Reproduce

将图表容器设置为 flex 布局下的元素，通过 flex 布局提供宽度（例如 flex: 1）

### Current Behavior

缩小页面，容器宽度会被 canvas 撑大，不会自动缩小。放大页面时表现正常。

### Expected Behavior

图表不撑开容器

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by xile611** [comment]
类似的问题： https://github.com/VisActor/VChart/issues/3349

<img width="862" alt="Image" src="https://github.com/user-attachments/assets/5e4a0ac2-8aef-4c0d-938b-ea8042c984fe" />

**Comment by xile611** [comment]
其他解决办法参考：


当使用 `display: flex` 的容器在页面缩小时不自动调整大小时，通常是由于**子元素的默认伸缩行为**或**容器/子元素的尺寸限制**导致的。以下是逐步解决方案：

---

### **1. 确保容器宽度可伸缩**
- **问题**：容器本身设置了固定宽度（如 `width: 1000px`）。
- **解决**：改用相对单位或百分比，使容器宽度自适应父元素：
  ```css
  .container {
    display: flex;
    width: 100%; /* 或 max-width: 100% */
  }
  ```

---

### **2. 允许子元素收缩**
- **问题**：子元素的 `flex-shrink` 被设为 `0`（默认是 `1`），或内容过长导致无法收缩。
- **解决**：
  - 确保子元素的 `flex-shrink` 值为 `1`（默认无需设置）：
    ```css
    .item {
      flex-shrink: 1; /* 默认值，通常不需要显式设置 */
    }
    ```
  - 覆盖子元素的 `min-width` 或 `min-height` 默认值：
    ```css
    .item {
      min-width: 0; /* 关键！允许内容挤压 */
      /* 或 min-height: 0（垂直布局时） */
    }
    ```

---

### **3. 处理内容溢出**
- **问题**：子元素内容（如文本、图片）过长，无法自动换行或缩放。
- **解决**：
  ```css
  .item {
    overflow-wrap: break-word; /* 允许长单词换行 */
    /* 或 */
    white-space: nowrap; /* 禁止换行但允许横向滚动 */
    /* 或 */
    overflow: hidden;
    text-overflow: ellipsis; /* 超出部分显示省略号 */
  }
  ```

---

### **4. 允许子元素换行**
- **问题**：子元素总宽度超过容器，但未换行。
- **解决**：设置 `flex-wrap: wrap` 并调整子元素基础宽度：
  ```css
  .container {
    display: flex;
    flex-wrap: wrap; /* 允许换行 */
  }
  .item {
    flex-basis: 200px; /* 设置子元素基础宽度 */
  }
  ```

---

### **5. 检查父级约束**
- **问题**：容器的父元素限制了尺寸（如固定宽度）。
- **解决**：确保父元素允许子容器收缩：
  ```css
  .parent {
    width: 100%; /* 或其他自适应值 */
  }
  ```

---

### **完整示例**
```html
<style>
  .container {
    display: flex;
    width: 100%;
    max-width: 1200px; /* 可选：限制最大宽度 */
    margin: 0 auto;
    flex-wrap: wrap; /* 可选：允许换行 */
  }
  .item {
    flex: 1; /* 自动伸缩 */
    min-width: 0; /* 关键！允许挤压 */
    overflow-wrap: break-word; /* 处理文本溢出 */
  }
</style>

<div class="container">
  <div class="item">长内容示例...</div>
  <div class="item">另一个子元素...</div>
</div>
```

---

通过以上步骤，Flex 容器和子元素应能根据页面缩放自动调整大小。如果问题仍未解决，建议使用浏览器开发者工具检查元素的盒模型和 CSS 属性，确认是否有其他样式冲突（如 `position: absolute` 或固定宽度覆盖）。
